apiVersion: v1
kind: Service
metadata:
  name: service-2-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: service-2
  ports:
  - name: cluster-port
    port: 8080
    targetPort: 8082
